[project]
name = "backend"
version = "0.1.0"
description = "backend of the chat-bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.16",
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
